import { img } from "@/lib/images";
import type {
  ClubEvent,
  Highlight,
  NewsArticle,
  Photo,
  TeamLead,
  TeamMember,
  Video,
} from "@/lib/types";

const base = { published: true, createdAt: "2026-01-01T00:00:00Z" };

export const events: ClubEvent[] = [
  {
    ...base,
    id: "freshers-2026",
    name: "Freshers' Night",
    date: "2026-08-21",
    year: 2026,
    description:
      "The first evening of the academic year, shot across the quad, the auditorium and the late-night afterparty.",
    coverImage: img.freshers,
    photoCount: 8,
  },
  {
    ...base,
    id: "cultural-fest-2026",
    name: "Cultural Fest",
    date: "2026-03-14",
    year: 2026,
    description:
      "Three days of stage light, colour and choreography — the club's largest coverage assignment of the spring.",
    coverImage: img.culturalFest,
    photoCount: 8,
  },
  {
    ...base,
    id: "sports-meet-2025",
    name: "Annual Sports Meet",
    date: "2025-11-09",
    year: 2025,
    description: "Track, field and the long telephoto lenses. Motion, dust and finish lines.",
    coverImage: img.sportsMeet,
    photoCount: 6,
  },
  {
    ...base,
    id: "tech-symposium-2025",
    name: "Tech Symposium",
    date: "2025-09-02",
    year: 2025,
    description: "Keynotes, demo tables and the quiet backstage moments between sessions.",
    coverImage: img.techSymposium,
    photoCount: 6,
  },
  {
    ...base,
    id: "graduation-2024",
    name: "Graduation Ceremony",
    date: "2024-06-18",
    year: 2024,
    description: "Robes, families and last frames on the lawn before the class disperses.",
    coverImage: img.graduation,
    photoCount: 6,
  },
  {
    ...base,
    id: "alumni-meet-2024",
    name: "Alumni Meet",
    date: "2024-02-24",
    year: 2024,
    description: "Returning cohorts, archive prints on the wall and a reunion in available light.",
    coverImage: img.alumniMeet,
    photoCount: 6,
  },
  {
    ...base,
    id: "halloween-2024",
    name: "Halloween Social",
    date: "2024-10-31",
    year: 2024,
    description: "High-contrast flash portraits and one very ambitious smoke machine.",
    coverImage: img.halloween,
    photoCount: 6,
  },
];

const photoPool = [
  img.fest1,
  img.fest2,
  img.fest3,
  img.fest4,
  img.fest5,
  img.storyFilmSet,
  img.storyDarkroom,
  img.nocturne,
  img.structure,
  img.fluid,
  img.lightbox1,
  img.filmStill,
];

const photographers = ["A. Menon", "R. Iyer", "S. Kulkarni", "T. Fernandes", "N. Bhatia", "P. Rao"];

const captions = [
  "Available light, wide open.",
  "Second frame of the sequence.",
  "Backstage, before the doors opened.",
  "Held for the reflection in the glass.",
  "Long exposure, tripod on the balcony.",
  "The last frame of the roll.",
];

export const photos: Photo[] = events.flatMap((event, ei) =>
  Array.from({ length: event.photoCount }, (_, i) => {
    const n = ei * 5 + i;
    return {
      ...base,
      id: `${event.id}-p${i + 1}`,
      eventId: event.id,
      imageUrl: photoPool[n % photoPool.length]!,
      orientation: (i % 3 === 1 ? "portrait" : "landscape") as Photo["orientation"],
      photographer: photographers[n % photographers.length]!,
      caption: captions[n % captions.length]!,
      tags: ["archive", event.name.toLowerCase().split(" ")[0]!],
    } satisfies Photo;
  })
);

export const highlights: Highlight[] = [
  {
    ...base,
    id: "nocturne",
    title: "Nocturne",
    description:
      "A night-long study of the campus after the last lecture — twelve frames selected from four hundred.",
    coverImage: img.nocturne,
    category: "photos",
    eventId: undefined,
    date: "2026-04-02",
    creator: "A. Menon",
    featured: true,
  },
  {
    ...base,
    id: "midnight-sun",
    title: "Midnight Sun",
    description: "Best Cinematography at the Spring Festival — a fourteen minute short.",
    coverImage: img.filmStill,
    category: "achievements",
    date: "2026-02-11",
    creator: "E. Rostova",
    featured: false,
  },
  {
    ...base,
    id: "structure",
    title: "Structure",
    description: "Concrete, stairwells and the geometry of the science block.",
    coverImage: img.structure,
    category: "photos",
    date: "2025-12-05",
    creator: "S. Kulkarni",
    featured: false,
  },
  {
    ...base,
    id: "fest-cut",
    title: "Cultural Fest — The Cut",
    description: "Three minutes assembled from nine hours of multi-camera festival footage.",
    coverImage: img.culturalFest,
    category: "videos",
    eventId: "cultural-fest-2026",
    date: "2026-03-20",
    creator: "R. Iyer",
    featured: false,
  },
  {
    ...base,
    id: "freshers-night",
    title: "Freshers' Night",
    description: "The club's full coverage of the opening night of the academic year.",
    coverImage: img.freshers,
    category: "events",
    eventId: "freshers-2026",
    date: "2026-08-22",
    creator: "Media Club",
    featured: false,
  },
  {
    ...base,
    id: "fluid",
    title: "Fluid",
    description: "High-speed water studies made in the club's improvised studio.",
    coverImage: img.fluid,
    category: "photos",
    date: "2025-10-18",
    creator: "N. Bhatia",
    featured: false,
  },
];

export const videos: Video[] = [
  {
    ...base,
    id: "midnight-sun-film",
    title: "Midnight Sun",
    description:
      "A short film shot over four nights on campus. Winner, Best Cinematography, Spring Festival.",
    thumbnail: img.filmStill,
    videoUrl: undefined,
    category: "student-projects",
    duration: "14:20",
    date: "2026-02-11",
    creator: "E. Rostova",
    featured: true,
  },
  {
    ...base,
    id: "fest-aftermovie",
    title: "Cultural Fest Aftermovie",
    description: "Multi-camera coverage of the three-day festival, cut to the closing set.",
    thumbnail: img.culturalFest,
    category: "event-coverage",
    eventId: "cultural-fest-2026",
    duration: "03:42",
    date: "2026-03-20",
    creator: "R. Iyer",
    featured: false,
  },
  {
    ...base,
    id: "darkroom-bts",
    title: "Inside the Darkroom",
    description: "Behind the scenes with the film division on a print night.",
    thumbnail: img.storyDarkroom,
    category: "behind-the-scenes",
    duration: "06:15",
    date: "2025-12-02",
    creator: "S. Kulkarni",
    featured: false,
  },
  {
    ...base,
    id: "lead-interview",
    title: "In Conversation: Photography Lead",
    description: "On building an archive that outlives its cohort.",
    thumbnail: img.storyFilmSet,
    category: "interviews",
    duration: "11:08",
    date: "2025-11-14",
    creator: "T. Fernandes",
    featured: false,
  },
  {
    ...base,
    id: "sports-reel",
    title: "Sports Meet — Reel",
    description: "Sixty seconds of the annual meet, vertical cut.",
    thumbnail: img.sportsMeet,
    category: "reels",
    eventId: "sports-meet-2025",
    duration: "01:00",
    date: "2025-11-10",
    creator: "P. Rao",
    featured: false,
  },
  {
    ...base,
    id: "club-promo",
    title: "Join the Media Club",
    description: "The recruitment film screened at the freshers' orientation.",
    thumbnail: img.freshers,
    category: "promotional",
    eventId: "freshers-2026",
    duration: "01:48",
    date: "2026-08-25",
    creator: "Media Club",
    featured: false,
  },
];

export const news: NewsArticle[] = [
  {
    ...base,
    id: "archive-goes-digital",
    title: "The Archive Goes Digital",
    subtitle:
      "Twelve years of club negatives, contact sheets and hard drives are being catalogued into a single public archive.",
    coverImage: img.storyDarkroom,
    category: "media-club",
    author: "A. Menon",
    publishedDate: "2026-08-28",
    readingTime: 6,
    featured: true,
    tags: ["archive", "photography", "club"],
    body: [
      {
        type: "paragraph",
        text: "For most of its life the Media Club's work lived in shoeboxes, shared drives and the occasional forgotten memory card. This year the club began the long job of consolidating all of it.",
      },
      { type: "heading", text: "Starting with the negatives" },
      {
        type: "paragraph",
        text: "The first pass covered the film era: several hundred rolls, scanned at archival resolution and matched to the events they were shot at.",
      },
      {
        type: "image",
        url: img.structure,
        alt: "Contact sheets laid out on a light table",
        caption: "Contact sheets from the 2019 festival, re-scanned this term.",
      },
      {
        type: "quote",
        text: "An archive is only useful if somebody can find the frame they are looking for.",
        attribution: "Photography Lead",
      },
      {
        type: "paragraph",
        text: "Cataloguing continues through the year, with new event coverage published to the archive within a week of each shoot.",
      },
    ],
  },
  {
    ...base,
    id: "cultural-fest-record",
    title: "Cultural Fest Draws Record Attendance",
    subtitle: "Three days, nine stages and the club's largest coverage team to date.",
    coverImage: img.culturalFest,
    category: "events",
    author: "R. Iyer",
    publishedDate: "2026-03-18",
    readingTime: 4,
    featured: false,
    tags: ["festival", "coverage"],
    body: [
      {
        type: "paragraph",
        text: "Fourteen photographers and six camera operators covered the festival across three days, filing images each night for next-morning publication.",
      },
      {
        type: "image",
        url: img.fest2,
        alt: "Performers on a lit stage during the cultural festival",
        caption: "Closing night on the main stage.",
      },
      {
        type: "paragraph",
        text: "The full gallery is available in the photo archive, organised by day and stage.",
      },
    ],
  },
  {
    ...base,
    id: "cinematography-award",
    title: "Midnight Sun Wins Best Cinematography",
    subtitle: "The club's fourteen-minute short takes the top craft prize at the Spring Festival.",
    coverImage: img.filmStill,
    category: "achievements",
    author: "T. Fernandes",
    publishedDate: "2026-02-12",
    readingTime: 3,
    featured: false,
    tags: ["film", "award"],
    body: [
      {
        type: "paragraph",
        text: "Shot over four consecutive nights with a two-person crew, the film was made almost entirely with equipment borrowed from the club's own kit room.",
      },
      {
        type: "paragraph",
        text: "A screening is planned for the end of term, followed by a short discussion with the crew.",
      },
    ],
  },
  {
    ...base,
    id: "new-kit-room",
    title: "Kit Room Reopens With Expanded Inventory",
    subtitle: "Members can now book bodies, lenses and lighting through a shared calendar.",
    coverImage: img.storyFilmSet,
    category: "campus",
    author: "N. Bhatia",
    publishedDate: "2025-12-08",
    readingTime: 3,
    featured: false,
    tags: ["club", "equipment"],
    body: [
      {
        type: "paragraph",
        text: "The refurbished kit room opened this month with a booking system that replaces the old sign-out sheet.",
      },
    ],
  },
  {
    ...base,
    id: "photowalk-series",
    title: "Weekly Photowalks Return",
    subtitle: "Open to every student, no equipment required beyond a phone.",
    coverImage: img.nocturne,
    category: "student-life",
    author: "P. Rao",
    publishedDate: "2025-10-21",
    readingTime: 2,
    featured: false,
    tags: ["photowalk", "students"],
    body: [
      {
        type: "paragraph",
        text: "The walks run every Friday evening and end with an informal edit session in the club room.",
      },
    ],
  },
  {
    ...base,
    id: "sports-coverage",
    title: "Covering the Annual Sports Meet",
    subtitle: "How the team handled fast action with borrowed telephoto glass.",
    coverImage: img.sportsMeet,
    category: "sports",
    author: "S. Kulkarni",
    publishedDate: "2025-11-11",
    readingTime: 5,
    featured: false,
    tags: ["sports", "technique"],
    body: [
      {
        type: "paragraph",
        text: "Shooting track events means committing to a position early and trusting the autofocus. The team split the field into four zones.",
      },
    ],
  },
];

export const teamLeads: TeamLead[] = [
  {
    ...base,
    id: "president",
    name: "Aarav Menon",
    role: "President",
    rank: "president",
    photo: undefined,
    bio: "Leads the club's direction, the archive programme and its editorial standards.",
    team: "Leadership",
    order: 0,
  },
  {
    ...base,
    id: "vice-president",
    name: "Riya Iyer",
    role: "Vice President",
    rank: "vice-president",
    photo: undefined,
    bio: "Coordinates event coverage, scheduling and the club's collaborations across campus.",
    team: "Leadership",
    order: 1,
  },
  {
    ...base,
    id: "videography-lead",
    name: "Sahil Kulkarni",
    role: "Videography Lead",
    rank: "lead",
    photo: undefined,
    bio: "Runs the film division: shoots, edits and the club's short-form output.",
    team: "Videography",
    order: 2,
  },
  {
    ...base,
    id: "photography-lead",
    name: "Tara Fernandes",
    role: "Photography Lead",
    rank: "lead",
    photo: undefined,
    bio: "Oversees stills coverage, the darkroom and the photographic archive.",
    team: "Photography",
    order: 3,
  },
  {
    ...base,
    id: "tech-lead",
    name: "Neel Bhatia",
    role: "Tech Lead",
    rank: "lead",
    photo: undefined,
    bio: "Maintains the kit room, the archive infrastructure and this website.",
    team: "Tech",
    order: 4,
  },
];

export const teamMembers: TeamMember[] = [
  {
    ...base,
    id: "vid-1",
    name: "Ishan Verma",
    role: "Camera Operator",
    bio: "Handles multi-camera event coverage and gimbal work.",
    skills: ["Camera", "Gimbal", "Lighting"],
    team: "Videography",
    order: 0,
  },
  {
    ...base,
    id: "vid-2",
    name: "Meera Nair",
    role: "Editor",
    bio: "Cuts the club's aftermovies and short-form reels.",
    skills: ["Premiere", "Color", "Sound"],
    team: "Videography",
    order: 1,
  },
  {
    ...base,
    id: "vid-3",
    name: "Kabir Shah",
    role: "Sound",
    bio: "Location sound and post mixing for interviews and shorts.",
    skills: ["Boom", "Mixing", "Foley"],
    team: "Videography",
    order: 2,
  },
  {
    ...base,
    id: "pho-1",
    name: "Ananya Rao",
    role: "Event Photographer",
    bio: "Covers festivals, sports and ceremonies for the archive.",
    skills: ["Events", "Flash", "Portrait"],
    team: "Photography",
    order: 0,
  },
  {
    ...base,
    id: "pho-2",
    name: "Dev Sharma",
    role: "Photojournalist",
    bio: "Documentary work around campus life and student stories.",
    skills: ["Reportage", "Street", "B&W"],
    team: "Photography",
    order: 1,
  },
  {
    ...base,
    id: "pho-3",
    name: "Leila Farooq",
    role: "Darkroom & Archive",
    bio: "Film processing, scanning and archival cataloguing.",
    skills: ["Film", "Scanning", "Cataloguing"],
    team: "Photography",
    order: 2,
  },
  {
    ...base,
    id: "tec-1",
    name: "Rohan Gupta",
    role: "Web Engineer",
    bio: "Builds and maintains the public archive site.",
    skills: ["React", "TypeScript", "Databases"],
    team: "Tech",
    order: 0,
  },
  {
    ...base,
    id: "tec-2",
    name: "Sara Qureshi",
    role: "Kit Room Manager",
    bio: "Runs equipment bookings, maintenance and inventory.",
    skills: ["Logistics", "Maintenance"],
    team: "Tech",
    order: 1,
  },
];
