/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as EventsRouteImport } from './routes/events'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as HighlightsIndexRouteImport } from './routes/highlights.index'
import { Route as HighlightsHighlightIdRouteImport } from './routes/highlights.$highlightId'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsArticleIdRouteImport } from './routes/news.$articleId'
import { Route as PhotosIndexRouteImport } from './routes/photos.index'
import { Route as PhotosEventIdRouteImport } from './routes/photos.$eventId'
import { Route as PhotosSlugRouteImport } from './routes/photos.$slug'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as VideosVideoIdRouteImport } from './routes/videos.$videoId'
import { Route as VideosEventEventIdRouteImport } from './routes/videos.event.$eventId'
import { Route as ApiPublicDriveFileIdRouteImport } from './routes/api/public/drive/$fileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightsIndexRoute = HighlightsIndexRouteImport.update({
  id: '/highlights/',
  path: '/highlights/',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightsHighlightIdRoute = HighlightsHighlightIdRouteImport.update({
  id: '/highlights/$highlightId',
  path: '/highlights/$highlightId',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsArticleIdRoute = NewsArticleIdRouteImport.update({
  id: '/news/$articleId',
  path: '/news/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosIndexRoute = PhotosIndexRouteImport.update({
  id: '/photos/',
  path: '/photos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosEventIdRoute = PhotosEventIdRouteImport.update({
  id: '/photos/$eventId',
  path: '/photos/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosSlugRoute = PhotosSlugRouteImport.update({
  id: '/photos/$slug',
  path: '/photos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosVideoIdRoute = VideosVideoIdRouteImport.update({
  id: '/videos/$videoId',
  path: '/videos/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosEventEventIdRoute = VideosEventEventIdRouteImport.update({
  id: '/videos/event/$eventId',
  path: '/videos/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDriveFileIdRoute = ApiPublicDriveFileIdRouteImport.update({
  id: '/api/public/drive/$fileId',
  path: '/api/public/drive/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/creator': typeof CreatorRoute
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/highlights/$highlightId': typeof HighlightsHighlightIdRoute
  '/news/$articleId': typeof NewsArticleIdRoute
  '/photos/$eventId': typeof PhotosEventIdRoute
  '/photos/$slug': typeof PhotosSlugRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/highlights/': typeof HighlightsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/photos/': typeof PhotosIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/videos/event/$eventId': typeof VideosEventEventIdRoute
  '/api/public/drive/$fileId': typeof ApiPublicDriveFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/creator': typeof CreatorRoute
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/highlights/$highlightId': typeof HighlightsHighlightIdRoute
  '/news/$articleId': typeof NewsArticleIdRoute
  '/photos/$eventId': typeof PhotosEventIdRoute
  '/photos/$slug': typeof PhotosSlugRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/highlights': typeof HighlightsIndexRoute
  '/news': typeof NewsIndexRoute
  '/photos': typeof PhotosIndexRoute
  '/videos': typeof VideosIndexRoute
  '/videos/event/$eventId': typeof VideosEventEventIdRoute
  '/api/public/drive/$fileId': typeof ApiPublicDriveFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/creator': typeof CreatorRoute
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/highlights/$highlightId': typeof HighlightsHighlightIdRoute
  '/news/$articleId': typeof NewsArticleIdRoute
  '/photos/$eventId': typeof PhotosEventIdRoute
  '/photos/$slug': typeof PhotosSlugRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/highlights/': typeof HighlightsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/photos/': typeof PhotosIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/videos/event/$eventId': typeof VideosEventEventIdRoute
  '/api/public/drive/$fileId': typeof ApiPublicDriveFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/archive'
    | '/auth'
    | '/creator'
    | '/events'
    | '/privacy'
    | '/register'
    | '/search'
    | '/team'
    | '/terms'
    | '/highlights/$highlightId'
    | '/news/$articleId'
    | '/photos/$eventId'
    | '/photos/$slug'
    | '/videos/$videoId'
    | '/highlights/'
    | '/news/'
    | '/photos/'
    | '/videos/'
    | '/videos/event/$eventId'
    | '/api/public/drive/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archive'
    | '/auth'
    | '/creator'
    | '/events'
    | '/privacy'
    | '/register'
    | '/search'
    | '/team'
    | '/terms'
    | '/highlights/$highlightId'
    | '/news/$articleId'
    | '/photos/$eventId'
    | '/photos/$slug'
    | '/videos/$videoId'
    | '/highlights'
    | '/news'
    | '/photos'
    | '/videos'
    | '/videos/event/$eventId'
    | '/api/public/drive/$fileId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/archive'
    | '/auth'
    | '/creator'
    | '/events'
    | '/privacy'
    | '/register'
    | '/search'
    | '/team'
    | '/terms'
    | '/highlights/$highlightId'
    | '/news/$articleId'
    | '/photos/$eventId'
    | '/photos/$slug'
    | '/videos/$videoId'
    | '/highlights/'
    | '/news/'
    | '/photos/'
    | '/videos/'
    | '/videos/event/$eventId'
    | '/api/public/drive/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchiveRoute: typeof ArchiveRoute
  AuthRoute: typeof AuthRoute
  CreatorRoute: typeof CreatorRoute
  EventsRoute: typeof EventsRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  HighlightsHighlightIdRoute: typeof HighlightsHighlightIdRoute
  NewsArticleIdRoute: typeof NewsArticleIdRoute
  PhotosEventIdRoute: typeof PhotosEventIdRoute
  PhotosSlugRoute: typeof PhotosSlugRoute
  VideosVideoIdRoute: typeof VideosVideoIdRoute
  HighlightsIndexRoute: typeof HighlightsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  PhotosIndexRoute: typeof PhotosIndexRoute
  VideosIndexRoute: typeof VideosIndexRoute
  VideosEventEventIdRoute: typeof VideosEventEventIdRoute
  ApiPublicDriveFileIdRoute: typeof ApiPublicDriveFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlights/': {
      id: '/highlights/'
      path: '/highlights'
      fullPath: '/highlights/'
      preLoaderRoute: typeof HighlightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlights/$highlightId': {
      id: '/highlights/$highlightId'
      path: '/highlights/$highlightId'
      fullPath: '/highlights/$highlightId'
      preLoaderRoute: typeof HighlightsHighlightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$articleId': {
      id: '/news/$articleId'
      path: '/news/$articleId'
      fullPath: '/news/$articleId'
      preLoaderRoute: typeof NewsArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/': {
      id: '/photos/'
      path: '/photos'
      fullPath: '/photos/'
      preLoaderRoute: typeof PhotosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/$eventId': {
      id: '/photos/$eventId'
      path: '/photos/$eventId'
      fullPath: '/photos/$eventId'
      preLoaderRoute: typeof PhotosEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/$slug': {
      id: '/photos/$slug'
      path: '/photos/$slug'
      fullPath: '/photos/$slug'
      preLoaderRoute: typeof PhotosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$videoId': {
      id: '/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/videos/$videoId'
      preLoaderRoute: typeof VideosVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/event/$eventId': {
      id: '/videos/event/$eventId'
      path: '/videos/event/$eventId'
      fullPath: '/videos/event/$eventId'
      preLoaderRoute: typeof VideosEventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/drive/$fileId': {
      id: '/api/public/drive/$fileId'
      path: '/api/public/drive/$fileId'
      fullPath: '/api/public/drive/$fileId'
      preLoaderRoute: typeof ApiPublicDriveFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchiveRoute: ArchiveRoute,
  AuthRoute: AuthRoute,
  CreatorRoute: CreatorRoute,
  EventsRoute: EventsRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  HighlightsHighlightIdRoute: HighlightsHighlightIdRoute,
  NewsArticleIdRoute: NewsArticleIdRoute,
  PhotosEventIdRoute: PhotosEventIdRoute,
  PhotosSlugRoute: PhotosSlugRoute,
  VideosVideoIdRoute: VideosVideoIdRoute,
  HighlightsIndexRoute: HighlightsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  PhotosIndexRoute: PhotosIndexRoute,
  VideosIndexRoute: VideosIndexRoute,
  VideosEventEventIdRoute: VideosEventEventIdRoute,
  ApiPublicDriveFileIdRoute: ApiPublicDriveFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
